.TH GIGGLE 1 "may  8, 2007"
.SH NAME
giggle \- Gtk+ interface to git trees 
.SH SYNOPSIS
.B giggle
.RI 
.SH DESCRIPTION
.PP
\fBgiggle\fP is a graphical frontend for the git directory tracker (think of gitk on GTK+).
.br
.SH AUTHOR
giggle was written by Carlos Garnacho <carlosg@gnome.org> Mikael Hallendal <micke@imendio.com> Richard Hult <richard@imendio.com>.
.PP
This manual page was written by Andrea Corradi <lash@unstable.it>,
for the Debian project (but may be used by others).
